extends Area

class_name Pickup

enum PICKUP_TYPES {CHAINGUN, CHAINGUN_AMMO, 
	SHOTGUN, SHOTGUN_AMMO, 
	FLAMETHROWER, FLAMETHROWER_AMMO,
	ROCKET_LAUNCHER, ROCKET_LAUNCHER_AMMO,
	HEALTH,
	BLUE_KEY, GREEN_KEY, YELLOW_KEY}

export(PICKUP_TYPES) var pickup_type
export var ammo = 10
